### ISSUE TITLE
REQUEST - SUPPORT FOR VERSION 1.19

### ISSUE THREAD

**Issue by PlesCZ** [SentixDev/squaremarker#2]
Hi, please support version 1.19. 
Server log when running the plugin on version 1.19.
https://pastebin.com/raw/rZ5NuBbq

**Comment by SentixDev** [comment]
Hi, I will support 1.19 as soon as squaremap is officially released for 1.19. No test-build or experimental release. BTW even paper 1.19 builds are still early, experimental builds.

**Comment by mrniddala** [comment]
Hello @SentixDev, it is out now 🥰
Greetings.

**Comment by jaknz** [comment]
I came here to second this. Yes please! 😄

**Comment by SentixDev** [comment]
https://github.com/SentixDev/squaremarker/releases/tag/1.19-v1.0.1
