### ISSUE TITLE
squaremarker not loading on 1.19.1

### ISSUE THREAD

**Issue by netcore10** [SentixDev/squaremarker#8]
Just doesn't let the server launch https://mclo.gs/FeyIqOz (quilt uses fabric mappings, no worries there)

**Comment by jpenilla** [comment]
I think this is fixed in https://github.com/SentixDev/squaremarker/commit/040e65e89c2776f56a290c411b243156f5430929 - it's just not in a release yet.

**Comment by jpenilla** [comment]
Fixed in https://github.com/SentixDev/squaremarker/releases/tag/1.19.3-v1.0.3, for 1.19.1 you will need to compile the previously linked commit
